name: Build Android APK

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  staging:
    name: v1.5 source staging
    runs-on: ubuntu-latest
    steps:
      - run: echo "v1.5 source upload staging"
